### Create new report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Skoda",
  "model": "Octavia",
  "year": 2010,
  "mileage": 10000,
  "price": 100000,
  "lat": 0,
  "lng": 0
}


### Approve a report
PATCH http://localhost:3000/reports/3/approve
Content-Type: application/json

{
  "approved": false
}